@baseUrl = http://localhost:5000
@ip = 14.152.94.1

###

# @name Info
# Retrieves comprehensive GeoIP, ASN, and reputation data for a specific IP address.
GET {{baseUrl}}/api/ip/info/{{ip}}
content-type: application/json

response_headers:
```
Content-Type: application/json
x-risk-score: 9
x-country-code: CN
x-cache: miss
x-ignore: false
```

@name FullIpInfo
# Retrieves comprehensive GeoIP, ASN, and reputation data for a specific IP address.
GET http://localhost:5000/api/ip/info/14.152.94.1
content-type: application/json

response:
```json
{
  "ip": {
    "address": "14.152.94.1",
    "broadcast": "14.152.95.255",
    "network": "14.152.80.0",
    "prefix": 20,
    "version": 4
  },
  "location": {
    "continent": "Asia",
    "country_code": "CN",
    "country_name": "China"
  },
  "organization": {
    "asn_description": "",
    "asn_name": "CT-DONGGUAN-IDC CHINANET Guangdong province network",
    "asn_number": 134763
  },
  "security": {
    "reasons": [
      "rbl:firehol_level1"
    ],
    "risk_score": 9
  }
}
```
###

# @name Check
# Simplified response focused on reputation and risk assessment.
GET {{baseUrl}}/api/ip/check/{{ip}}

response_headers:
```
Content-Type: application/json
x-risk-score: 9
x-cache: miss
x-ignore: false
```

response:
```json
{
  "ip": "14.152.94.1",
  "reasons": [
    "rbl:firehol_level1"
  ],
  "risk_score": 9
}
```
###

# @name Quick
# Optimized for firewalls and middleware. Returns risk score in body and X-Risk-Score header.
GET {{baseUrl}}/api/ip/quick/{{ip}}

response_headers:
```
Content-Type: application/json
x-risk-score: 9
x-cache: miss
x-ignore: false
```

response:
```json
{
  "risk_score": 9
}
```